### ISSUE TITLE
disable idle timer to keep screen on while playing.

### ISSUE THREAD

**Issue by jandersen** [cooperhewitt/Planetary#228] opened 2011-10-08 23:20 UTC
You can disable the idle timer through the idleTimerDisabled property of the shared UIApplication object:
// Disable the idle timer
[[UIApplication sharedApplication] setIdleTimerDisabled: YES];

**Comment by RandomEtc** [comment] 2011-10-09 05:51
Closing - is a dupe of #143 :)

Didn't do it because it seemed overly complicated in its interactions with the music library, but maybe we can get to it when we fix things up for iOS 5.

**Closed as completed by RandomEtc** 2011-10-09 05:51 UTC

**Comment by jandersen** [comment] 2011-10-09 05:57
excellent.
